--- 
abstract: Include Amazon objects on your page.
author: Marcus Ramberg <mramberg@cpan.org
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MojoMojo-Formatter-Amazon
no_index: 
  directory: 
    - inc
    - t
requires: 
  MojoMojo: 0
  Net::Amazon: 0
tests: t/amazon.t
version: undef
